### ISSUE TITLE
FQDN with trailing dot does not work with HTTPS

### ISSUE THREAD

**Issue by tyllmoritz** [oflebbe/lug-tuebingen.de#3]
Beim aufrufen der URL "https://lug-tuebingen.de./" kommt ein Fehler, da die Domain mit Punkt am Ende nicht bei der Server Name Indication (SNI) berücksichtigt wird.
Deshalb funktionieren HTTPS-Verbindungen nicht, wenn die Domain mit Punkt am Ende eingegeben wird.

Fehler:
"421 Misdirected Request"

"The client needs a new connection for this request as the requested host name does not match the Server Name Indication (SNI) in use for this connection."

**Comment by oflebbe** [comment]
Ja das ist so. Habe ich aus Versehen irgendwo eine URL mit einem abschliessenden Punkt hinterlassen?

**Comment by tyllmoritz** [comment]
Nein, ist also kein Problem. Kann geschlossen werden.

Nur für den Nerd in mir wäre es cool, wenn die Seite auch mit Punkt funktionieren würde.
